"use strict";
exports.__esModule = true;
var ClaseLibreria_1 = require("./ClaseLibreria");
var ClaseLibro_1 = require("./ClaseLibro");
var ClaseCliente_1 = require("./ClaseCliente");
var ClaseRevista_1 = require("./ClaseRevista");
var arrayAutores = ["Shakespare", "Paulo Cohelo", "Stephen King"];
var arrayGeneros = ["Terror", "Comedia", "Autoayuda"];
var revista1 = new ClaseRevista_1.Revista("Magazine", "Clarin", 200, 20, 2021);
var revista2 = new ClaseRevista_1.Revista("Caras", "Empresa Caras", 290, 21, 2021);
var revista3 = new ClaseRevista_1.Revista("El Gráfico", "Grupo Clarin", 340, 34, 2021);
var libro1 = new ClaseLibro_1.Libro("Quién se llevó mi queso", "Spencer Jonson", 2300, "Desarrollo Personal", "Es un libro muy interesante", 106);
var libro2 = new ClaseLibro_1.Libro("El señor de los Anillos", "J.R.Tolkien", 6540, "Literatura fantástica", "Es un libro muy interesante", 390);
var libro3 = new ClaseLibro_1.Libro("Alicia en el Pais de las Maravillas", "Lewis Carol", 2990, "Fantasía", "Es un libro muy interesante", 120);
var cliente1 = new ClaseCliente_1.Cliente("Pedro", "Lopez", "20123455", "San Martin 1120", "2901345678", arrayAutores, arrayGeneros, 10);
var cliente2 = new ClaseCliente_1.Cliente("Jose", "FLores", "30233999", "Gdor. Paz 1420", "2901546789", arrayAutores, arrayGeneros, 15);
var cliente3 = new ClaseCliente_1.Cliente("Laura", "Lamas", "23678903", "Gdor. Deloqui 350", "2901608877", arrayAutores, arrayGeneros, 30);
var arrayLibros = [libro1, libro2, libro3];
var arrayRevistas = [revista1, revista2, revista3];
var arrayClientes = [cliente1, cliente2, cliente3];
var libreria = new ClaseLibreria_1.Libreria(arrayLibros, arrayRevistas, arrayClientes);
console.log("El precio es del libro " + libro1.getNombre() + " es: " + libreria.calcularPrecio(cliente1, libro1) + " para el cliente " + cliente1.getApellidoCliente());
console.log("El precio es del libro " + libro1.getNombre() + " es: " + libreria.calcularPrecio(cliente2, libro1) + " para el cliente " + cliente2.getApellidoCliente());
console.log("El precio es del libro " + libro1.getNombre() + " es: " + libreria.calcularPrecio(cliente3, libro1) + " para el cliente " + cliente3.getApellidoCliente());
